name: bPermsCommands
main: net.rymate.bpermscommands.bPermsCommands
depend: [ bPermissions ]
version: 1.0
author: rymate1234
website: www.rymate.co.uk
description: Extra commands for bPermissions.
commands:
    setgroup:
      description: Sets the group of a player.
      usage: /<command> <player> <group> [world]
      permission: bPermsCommands.setgroup
      permission-message: You can't do that :(
    setprefix:
      description: Sets the prefix of a group or player
      usage: /<command> <player/group> <prefix> [world]
      permission: bPermsCommands.setprefix
      permission-message: You can't do that :(
    setprefix:
      description: Adds a permissions node to a group or user
      usage: /<command> <player/group> <permission> [world]
      permission: bPermsCommands.setprefix
      permission-message: You can't do that :(